image = "/Users/kargo/.local/share/smolvm/smolmachines-dev.tar"
net = true

cmd = ["sh", "-c", "/bin/zsh"]

[network]
allow_hosts = [
    "localhost",
    "api.anthropic.com",
    "api.openai.com",
    "openrouter.ai",
    "models.dev",
    "github.com",
    "api.github.com",
    "raw.githubusercontent.com",
    "registry.npmjs.org",
    "archive.ubuntu.com",
    "security.ubuntu.com"
]

[dev]
volumes = ["./:/app"]

[auth]
ssh_agent = false

